<div class="bg-light-grey">
    <div class="container-fluid">
        <div class="page-header">
            <h1><?php echo $this->translate('Portal'); ?></h1>
        </div>
        <div class="row vpadded-row">
            <div class="col-md-5">
                <div class="container">
                    <div class="row">
                        <h3>Portal Stuff Here</h3>
                </div>
            </div>
        </div>
    </div>
</div>