<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Foundation App'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->zfcUserIdentity()? $this->url('application/innerpage') : $this->url('home') ?>"><span class="brand-logo glyphicon glyphicon-tree-deciduous"></span>&nbsp;<?php echo $this->translate('<em>foundation</em><b>App</b>') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav pull-right">
                        <!-- Test if the User is connected -->
                        <?php if(!$this->zfcUserIdentity()): ?>
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li class=""><a href="<?php echo $this->url('application/supportingpage') ?>"><?php echo $this->translate('Pricing') ?></a></li>
                        <li class=""><a href="<?php echo $this->url('application/supportingpage') ?>"><?php echo $this->translate('Partners') ?></a></li>
                        <li class=""><a href="<?php echo $this->url('application/supportingpage') ?>"><?php echo $this->translate('Blog') ?></a></li>

                            <!-- display regster and login buttons -->
                            <li class="btn-register"><a href="<?php echo $this->url('zfcuser/register') ?>"><?php echo $this->translate('Register') ?></a></li>
                            <li class="btn-login"><a href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('Login') ?></a></li>
                        <?php else: ?>
                            <li class=""><a href="<?php echo $this->url('application/innerpage') ?>"><?php echo $this->translate('Inner Page 1') ?></a></li>
                            <li class=""><a href="<?php echo $this->url('application/innerpage') ?>"><?php echo $this->translate('Inner Page 2') ?></a></li>
                            <li class=""><a href="<?php echo $this->url('application/innerpage') ?>"><?php echo $this->translate('Inner Page 3') ?></a></li>

                            <!-- show the 'display name' of the user -->
                            <li class=""><a href="<?php echo $this->url('zfcuser') ?>"><span class="glyphicon glyphicon-user"></span>&nbsp;</span>
                                <?php echo $this->zfcUserIdentity()->getEmail(); ?>
                            </a>a></li>
                        <?php endif?>

                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

            <?php echo $this->content; ?>



            <footer>
                <div class="container">
                <p>&copy; <?php echo date('Y') ?> JohnD Foundation App. <?php echo $this->translate('All rights reserved.') ?></p>
                    </div>
            </footer>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
