<div class="bg-light-grey">
    <div class="container">
        <div class="row vpadded-row">
            <div class="col-md-5">
                <h1> <?php echo sprintf($this->translate('%s%s&nbsp;Foundation App...%s'), '<span class="brand-emphasis">', '<span class="brand-logo glyphicon glyphicon-tree-deciduous"></span>', '</span>') ?></h1>
                <p class="spaced-text vpadding30"><?php echo sprintf($this->translate('This Foundation App is a work in progress based on the Zend 2 MVC Skeleton App. I will be building on the app on the %sGit Hub Repo%s'), '<a href="https://github.com/JohnD-EE/FoundationApp" target="_blank">', '</a>') ?></p>
            </div>
            <div class="col-md-7">
                <img src="http://placekitten.com/g/600/400" class="img-responsive img-rounded center-block"
                     alt="Responsive image">
            </div>
        </div>
    </div>
</div>

<div class="bg-dark">
    <div class="container">
        <div class="row vpadded-row">

            <div class="col-md-8">
                <h2>Register</h2>
                <p>Some enticing words or pictures as encouragement to persuade a user to sign up...</p>
                </div>
            <div class="col-md-4">

                <form method="post" action="/user/register">
                    <div class="form-group ">
                        <label class="control-label">Your Email</label>
                        <input name="email" type="email" class="form-control" placeholder="Enter Your Email" value="">    </div>

                    <div class="form-group ">
                        <button type="submit" name="submit" class="btn-register btn-wide" value="">Register</button>    </div>

                </form>

            </div>

        </div>
    </div>
</div>

<div class="">
    <div class="container">
        <div class="row vpadded-row">

            <div class="col-md-4">
                <div class="">

                    <div class="text-center">
                        <p class="spaced-text vpadding30"><?php echo $this->translate('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse blandit arcu nibh, in euismod mi ullamcorper nec. Aliquam erat volutpat. Morbi vehicula id odio id iaculis. Nulla quis eleifend nisl, at porttitor nunc.') ?></p>
                        <p><img src="http://placekitten.com/g/220/220" class="img-circle img-responsive center-block"
                                alt="Responsive image"></p>
                    </div>
                </div>

            </div>

            <div class="col-md-4">
                <div class="">

                    <div class="text-center">
                        <p class="spaced-text vpadding30"><?php echo $this->translate('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse blandit arcu nibh, in euismod mi ullamcorper nec. Aliquam erat volutpat. Morbi vehicula id odio id iaculis. Nulla quis eleifend nisl, at porttitor nunc.') ?></p>
                        <p><img src="http://placekitten.com/g/220/220" class="img-circle img-responsive center-block"
                                alt="Responsive image"></p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="">

                    <div class="text-center">
                        <p class="spaced-text vpadding30"><?php echo $this->translate('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse blandit arcu nibh, in euismod mi ullamcorper nec. Aliquam erat volutpat. Morbi vehicula id odio id iaculis. Nulla quis eleifend nisl, at porttitor nunc.') ?></p>
                        <p><img src="http://placekitten.com/g/220/220" class="img-circle img-responsive center-block"
                                alt="Responsive image"></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
