<?php
/**
 * Created by PhpStorm.
 * User: John
 * Date: 06/07/2015
 * Time: 21:49
 */

?>

<div class="bg-dark">
    <div class="container">
        <div class="row vpadded-row ">
            <div class="col-md-12 text-center">
                <h1>This is an Inner Page</h1>
                <h3>This area is for bespoke content.</h3>
            </div>
        </div>
    </div>
</div>

<div class="bg-light-grey">
    <div class="container">
        <div class="row vpadded-row">
            <div class="col-md-6">
                <h2>Bespoke Application Content</h2>
                <p>This area will be for the bespoke application</p>
            </div>
            <div class="col-md-6">
                <h2>Bespoke Application Content</h2>
                <p>This area will be for the bespoke application</p>
            </div>

        </div>
    </div>
</div>
