<?php
/**
 * Created by PhpStorm.
 * User: John
 * Date: 05/07/2015
 * Time: 21:25
 */
?>

<div class="bg-dark">
    <div class="container">
        <div class="row vpadded-row ">

            <div class="col-md-12 text-center">
                <h1>This is a Supporting Page</h1>

                <h3>This could be for About, FAQs, Pricing Plans, Partners, Contact etc.</h3>
            </div>
        </div>
    </div>
</div>

<div class="bg-light-grey">
    <div class="container">
        <div class="row vpadded-row">
            <div class="col-md-8">
                <img src="https://placeimg.com/500/350/tech/grayscale" class="img-responsive img-rounded center-block"
                     alt="Responsive image">
            </div>
            <div class="col-md-4">
                <h2>Topic heading</h2>
                <p>Here are some words to accompany the video, infographic, picture etc. If needed, the picutre could
                    span the whole width of the page with this text overlaid on top</p>
            </div>

        </div>
    </div>
</div>

<div class="">
    <div class="container">
        <div class="row vpadded-row">

            <div class="col-md-4">
                <h2>Topic heading</h2>
                <p>Here are some words to accompany the video, infographic, picture etc. If needed, the picutre could
                    span the whole width of the page with this text overlaid on top</p>
            </div>
            <div class="col-md-8">
                <img src="https://placeimg.com/500/350/animals/grayscale" class="img-responsive img-rounded center-block"
                     alt="Responsive image">
            </div>
        </div>
    </div>
</div>

<div class="bg-light-grey">
    <div class="container">
        <div class="row vpadded-row">
            <div class="col-md-8">
                <img src="https://placeimg.com/500/350/arch/grayscale" class="img-responsive img-rounded center-block"
                     alt="Responsive image">
            </div>
            <div class="col-md-4">
                <h2>Topic heading</h2>
                <p>Here are some words to accompany the video, infographic, picture etc. If needed, the picutre could
                    span the whole width of the page with this text overlaid on top</p>
            </div>

        </div>
    </div>
</div>