<div class="bg-light-grey">
    <div class="container-fluid">
        <div class="page-header">
            <h1><?php echo $this->translate('My Account'); ?></h1>
        </div>
        <div class="row vpadded-row">
            <div class="col-md-5">
                <div class="container">
                    <div class="row">
                        <div
                            style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
                        <h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
                        <a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>
                            ]</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>