<div class="bg-light-grey">
    <div class="container">
        <div class="page-header">
            <h1><?php echo $this->translate('Register'); ?></h1>
        </div>
        <div class="row vpadded-row">
            <div class="col-md-5">



<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>

<?php foreach ($form as $element) : ?>

    <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <?php
        if ('submit' != $element->getAttribute('type')) { ?>
            <label class="control-label"><?php echo $element->getLabel() ?></label>
            <?php
            $element->setAttribute('class', 'form-control')
                ->setAttribute('placeholder', $element->getLabel());
        } else {
            $element->setAttribute('class', 'btn btn-register');
        }
        if ($element instanceof Zend\Form\Element\Captcha) {
            echo $this->formCaptcha($element);
        } else {
            echo $this->formElement($element);
        }
        if ($this->formElementErrors($element)) : ?>
            <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<p class="help-block">')
                ->setMessageSeparatorString('</p><p class="help-block">')
                ->setMessageCloseString('</p>')
                ->render($element);
            ?>
        <?php endif; ?>
    </div>

<?php
endforeach;
if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
<?php endif ?>
<?php echo $this->form()->closeTag() ?>

            </div>
            <div class="col-md-5 col-md-offset-2">
              <div class="well">
            <h3>Why Register?</h3>
                <ul>
                    <li>Great reason one</li>
                    <li>Great reason two</li>
                    <li>Great reason three</li>
                    <li>An infographic or video would be ideal here...</li>
                </ul>
              </div>
            </div>
        </div>
    </div>
</div>